CREATE DATABASE QLSINHVIEN
GO
USE QLSINHVIEN
GO

CREATE TABLE PHONGBAN 
(
	MAPHONGBAN INT  PRIMARY KEY,
	TENPHONGBAN NVARCHAR(50) NOT NULL
)
GO


CREATE TABLE KHOA 
(
	MAKHOA INT  PRIMARY KEY,
	TENKHOA NVARCHAR (50) NOT NULL,
	MAPHONGBAN INT,
	SDT CHAR(12) NOT NULL
	FOREIGN KEY  (MAPHONGBAN) REFERENCES PHONGBAN(MAPHONGBAN) 
)
GO

CREATE TABLE LOP 
(
	MALOP INT  PRIMARY KEY,
	TENLOP NVARCHAR (10),
	KHOA INT,
	HEDAOTAO NVARCHAR (15),
	NAMNHAPHOC INT,
	MAKHOA INT,
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
)
GO

CREATE TABLE USERS 
(
	MAUSERS INT  PRIMARY KEY,
	HOTEN NVARCHAR (25),
	SDT CHAR (10),
	NGAYSINH DATE ,
	EMAIL NVARCHAR(25),
	DIACHI NVARCHAR (100),
	PASS NVARCHAR(25),
	HOCVAN NVARCHAR (50),
	MAKHOA INT,
	MALOP INT,
	MAPHONGBAN INT,
	ROLE INT ,
	NGAYVAOTRUONG DATE,
	FOREIGN KEY (MAPHONGBAN) REFERENCES PHONGBAN (MAPHONGBAN),
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
	FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
)
GO

CREATE TABLE THANNHAN 
(
	TENTHANNHAN NVARCHAR (50),
	SDT CHAR (12) NOT NULL,
	QUANHE NVARCHAR (15),
	MAUSERS INT PRIMARY KEY,
	FOREIGN KEY (MAUSERS) REFERENCES  USERS (MAUSERS)
)
GO

CREATE TABLE MONHOC 
(
	MAMONHOC INT  PRIMARY KEY,
	TENMONHOC NVARCHAR (20),
	SODVTINCHI INT,
	MAKHOA INT,
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA)
)
GO

CREATE TABLE MONHOC_LOP 
(
	MALOP INT,
	MAMONHOC INT,
	HOCKY NVARCHAR(25),
	MAUSERS INT,
	PRIMARY KEY (MALOP, MAMONHOC),
	FOREIGN KEY (MAUSERS) REFERENCES  USERS (MAUSERS),
	FOREIGN KEY (MALOP ) REFERENCES LOP (MALOP),
	FOREIGN KEY (MAMONHOC) REFERENCES MONHOC (MAMONHOC)
)
GO

CREATE TABLE DIEMTHI 
(
	MAMONHOC INT,
	MAUSERS INT, 
	DIEMHESO1 TINYINT NOT NULL,
	DIEMHESO2 TINYINT NOT NULL,
	DIEMTHI TINYINT NOT NULL,
	DIEMTRUNGBINH TINYINT,
	XEPLOAI NVARCHAR(10),
	PRIMARY KEY (MAMONHOC, MAUSERS),
	FOREIGN KEY (MAUSERS) REFERENCES  USERS (MAUSERS),
	FOREIGN KEY (MAMONHOC) REFERENCES MONHOC (MAMONHOC)
)
GO

--MAUSERS INT  PRIMARY KEY,
--	HOTEN NVARCHAR (25),
--	SDT CHAR (10),
--	NGAYSINH DATE ,
--	EMAIL NVARCHAR(25),
--	DIACHI NVARCHAR (100),
--	PASS NVARCHAR(25),
--	HOCVAN NVARCHAR (50),
--	MAKHOA INT,
--	MALOP INT,
--	MAPHONGBAN INT,
--NGAYVAOTRUONG DATE,
set dateformat dmy

INSERT INTO KHOA VALUES (?,?,?,?)

INSERT INTO USERS VALUES (123, N' Monkey D Luffy', '0768170398',  ' 17/03/1998', 'lehoangg1703@gmail.com',  N' Thuyền Sunny Thousand', '123', null,  null, null, null, 0, null)
INSERT INTO USERS VALUES (234, N' Monkey D Luffy', '0768170398',  ' 17/03/1998', 'lehoangg1703@gmail.com',  N' Thuyền Sunny Thousand', '123', null,  null, null, null, 1, null)
INSERT INTO USERS VALUES (345, N' Monkey D Luffy', '0768170398',  ' 17/03/1998', 'lehoangg1703@gmail.com',  N' Thuyền Sunny Thousand', '123', null,  null, null, null, 2, null)

select * from PHONGBAN

select TENPHONGBAN from PHONGBAN

insert into KHOA values (958, N'CNTT', null, '098765432')
select * from KHOA
insert INTO PHONGBAN 
values (123, N'ABC')
insert PHONGBAN 
values (234, N'BCD')

SELECT MAPHONGBAN, MAKHOA, TENKHOA, SDT FROM KHOA

select * from KHOA
delete PHONGBAN where MAPHONGBAN = '789'