
SELECT FORMAT (getdate(), 'dd-MM-yyyy') as date
GO

CREATE DATABASE QLSINHVIEN
GO
USE QLSINHVIEN
GO

CREATE TABLE PHONGBAN 
(
	MAPHONGBAN INT  PRIMARY KEY,
	TENPHONGBAN NVARCHAR(50) NOT NULL
)
GO


CREATE TABLE KHOA 
(
	MAKHOA INT  PRIMARY KEY,
	TENKHOA NVARCHAR (50) NOT NULL,
	MAPHONGBAN INT,
	SDT CHAR(12) NOT NULL
	FOREIGN KEY  (MAPHONGBAN) REFERENCES PHONGBAN(MAPHONGBAN) 
)
GO

CREATE TABLE LOP 
(
	MALOP INT  PRIMARY KEY,
	TENLOP NVARCHAR (10),
	KHOA INT,
	HEDAOTAO NVARCHAR (50),
	NAMNHAPHOC INT,
	MAKHOA INT,
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
)
GO

CREATE TABLE USERS 
(
	MAUSERS INT  PRIMARY KEY,
	HOTEN NVARCHAR (25),
	SDT CHAR (10),
	NGAYSINH DATE ,
	EMAIL NVARCHAR(25),
	DIACHI NVARCHAR (100),
	PASS NVARCHAR(25),
	HOCVAN NVARCHAR (50),
	MAKHOA INT,
	MALOP INT,
	MAPHONGBAN INT,
	ROLE INT ,
	NGAYVAOTRUONG DATE,
	FOREIGN KEY (MAPHONGBAN) REFERENCES PHONGBAN (MAPHONGBAN),
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
	FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
)
GO

CREATE TABLE THANNHAN 
(
	TENTHANNHAN NVARCHAR (50),
	SDTTHANNHAN CHAR (12) NOT NULL,
	QUANHE NVARCHAR (15),
	MAUSERS INT PRIMARY KEY,
	FOREIGN KEY (MAUSERS) REFERENCES  USERS (MAUSERS)
)
GO

CREATE TABLE MONHOC 
(
	MAMONHOC INT  PRIMARY KEY,
	TENMONHOC NVARCHAR (20),
	SODVTINCHI INT,
	MAKHOA INT,
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA)
)
GO

CREATE TABLE MONHOC_LOP 
(
	MALOP INT,
	MAMONHOC INT,
	HOCKY NVARCHAR(25),
	MAUSERS INT,
	PRIMARY KEY (MALOP, MAMONHOC),
	FOREIGN KEY (MAUSERS) REFERENCES  USERS (MAUSERS),
	FOREIGN KEY (MALOP ) REFERENCES LOP (MALOP),
	FOREIGN KEY (MAMONHOC) REFERENCES MONHOC (MAMONHOC)
)
GO

CREATE TABLE DIEMTHI 
(
	MAMONHOC INT,
	MAUSERS INT, 
	DIEMHESO1 TINYINT NOT NULL,
	DIEMHESO2 TINYINT NOT NULL,
	DIEMTHI TINYINT NOT NULL,
	DIEMTRUNGBINH TINYINT,
	XEPLOAI NVARCHAR(10),
	PRIMARY KEY (MAMONHOC, MAUSERS),
	FOREIGN KEY (MAUSERS) REFERENCES  USERS (MAUSERS),
	FOREIGN KEY (MAMONHOC) REFERENCES MONHOC (MAMONHOC)
)
GO

--MAUSERS INT  PRIMARY KEY,
--	HOTEN NVARCHAR (25),
--	SDT CHAR (10),
--	NGAYSINH DATE ,
--	EMAIL NVARCHAR(25),
--	DIACHI NVARCHAR (100),
--	PASS NVARCHAR(25),
--	HOCVAN NVARCHAR (50),
--	MAKHOA INT,
--	MALOP INT,
--	MAPHONGBAN INT,
--NGAYVAOTRUONG DATE,
set dateformat dmy



INSERT INTO USERS VALUES (123, N' Monkey D Luffy', '0768170398',  ' 17/03/1998', 'lehoangg1703@gmail.com',  N' Thuyền Sunny Thousand', '123', null,  null, null, null, 0, null)
INSERT INTO USERS VALUES (234, N' Monkey D Luffy', '0768170398',  ' 17/03/1998', 'lehoangg1703@gmail.com',  N' Thuyền Sunny Thousand', '123', null,  null, null, null, 1, null)
INSERT INTO USERS VALUES (345, N' Monkey D Luffy', '0768170398',  ' 17/03/1998', 'lehoangg1703@gmail.com',  N' Thuyền Sunny Thousand', '123', null,  null, null, null, 2, null)



select TENPHONGBAN from PHONGBAN


select * from PHONGBAN
SELECT MAPHONGBAN, MAKHOA, TENKHOA, SDT FROM KHOA
select * from USERS
INSERT INTO USERS VALUES (0000, N' Monkey D Luffy', '0768170398',  ' 17/03/1998', 'lehoangg1703@gmail.com',  N' Thuyền Sunny Thousand', '123', N'Sinh viên',  1052, 756, null, 0,  ' 17/03/1998')
select * from KHOA
select * from USERS
SELECT  us.MAUSERS, us.HOTEN, us.SDT, us.NGAYSINH, us.EMAIL, us.DIACHI, us.PASS, us.HOCVAN, us.ROLE, us.NGAYVAOTRUONG, l.TENLOP, kh.TENKHOA, tn.TENTHANNHAN, tn.QUANHE, tn.SDTTHANNHAN
FROM USERS us, KHOA kh, LOP l, THANNHAN tn
WHERE (kh.MAKHOA = us.MAKHOA) AND  
				(l.MALOP = us.MALOP) AND (tn.MAUSERS = us.MAUSERS)
SELECT MALOP, TENLOP  FROM LOP
select kh.TENKHOA, lp.MALOP, lp.TENLOP, lp.KHOA, lp.HEDAOTAO, lp.NAMNHAPHOC from KHOA kh, LOP lp where kh.MAKHOA = lp.MAKHOA

select* from THANNHAN
insert THANNHAN values (N'Ronaldo', '098670179', N'ba', 0)

select * from USERS


insert USERS (MAUSERS, HOTEN, SDT, NGAYSINH, EMAIL, DIACHI, PASS, HOCVAN, MAKHOA, MALOP, MAPHONGBAN, ROLE, NGAYVAOTRUONG)
values (124, N'Nguyễn Văn A', '021312333', '24/03/1998', 'abc@gmail.com','TP.HCM', '24031998', N'Sinh viên', null, null, null, 2, '24/03/2021')

select * from PHONGBAN
select * from KHOA

select sv.HOTEN, sv.MAKHOA
from PHONGBAN pb, KHOA kh, USERS sv 
where pb.MAPHONGBAN = kh.MAPHONGBAN and kh.MAKHOA = sv.MAKHOA and sv.MAPHONGBAN = 475374

select *
from USERS sv, THANNHAN tn
where sv.MAUSERS = tn.MAUSERS and tn.MAUSERS = 21978225