DROP DATABASE QLSINHVIEN
GO
USE QLSINHVIEN
GO

CREATE TABLE PHONGBAN 
(
	MAPHONGBAN INT IDENTITY PRIMARY KEY,
	TENPHONGBAN NVARCHAR(50) NOT NULL
)
GO
insert into PHONGBAN VALUES (  N' Phòng đào tạo')

SELECT* FROM PHONGBAN

CREATE TABLE KHOA 
(
	MAKHOA INT IDENTITY PRIMARY KEY,
	TENKHOA NVARCHAR (50) NOT NULL,
	MAPHONGBAN INT,
	SDT CHAR(12) NOT NULL
	FOREIGN KEY  (MAPHONGBAN) REFERENCES PHONGBAN(MAPHONGBAN) 
)
GO

INSERT INTO KHOA VALUES (N'Khoa Công nghệ thông tin', 1, N'0986791794')

CREATE TABLE NHANVIEN 
(
	MANHANVIEN INT IDENTITY PRIMARY KEY,
	TENGIANGVIEN NVARCHAR (25),
	SDT CHAR (10),
	EMAIL NVARCHAR(25),
	PASS NVARCHAR(25),
	DIACHI NVARCHAR (100),
	CHUCVU NVARCHAR (50),
	ROLE INT  DEFAULT 0,  -- 0 ADMIN && 1 : STAFF
	MAKHOA INT,
	MAPHONGBAN INT,
	FOREIGN KEY (MAPHONGBAN) REFERENCES PHONGBAN (MAPHONGBAN),
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA)
)
GO

INSERT INTO NHANVIEN VALUES (N' Monkey D Luffy', N'0768170398', N'lehoangg1703@gmail.com', N'123', N'  Thuyền Sunny Thousand', N' Captain', 0, 1, 1)

INSERT INTO NHANVIEN VALUES (N' Nami', N'06374548', N'Nami@gmail.com', N'123', N'  Thuyền Sunny Thousand', N' Thuyền viên', 1, 1, 1)
INSERT INTO NHANVIEN VALUES (N' Nami', N'06374548', N'admin', N'123', N'  Thuyền Sunny Thousand', N' admin', 0, 2, 1)

CREATE TABLE LOP 
(
	MALOP INT IDENTITY PRIMARY KEY,
	TENLOP NVARCHAR (10),
	KHOA INT,
	HEDAOTAO NVARCHAR (15),
	NAMNHAPHOC INT,
	MAKHOA INT,
	MANHANVIEN INT,
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
	FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN (MANHANVIEN)
)
GO

CREATE TABLE SINHVIEN 
(
	MSSV INT  IDENTITY PRIMARY KEY,
	HOTENSINHVIEN NVARCHAR (50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	SDT CHAR (12) NOT NULL,
	PASS NVARCHAR(20),
	EMAIL NVARCHAR (25) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	MAKHOA INT NOT NULL,
	MALOP INT,
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
	FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
)
GO

CREATE TABLE THANNHAN 
(
	MATHANNHAN INT IDENTITY PRIMARY KEY,
	TENTHANNHAN NVARCHAR (50),
	SDT CHAR (12) NOT NULL,
	QUANHE NVARCHAR (15),
	MSSV INT,
	MANHANVIEN INT,
	FOREIGN KEY (MSSV) REFERENCES SINHVIEN (MSSV),
	FOREIGN KEY (MANHANVIEN) REFERENCES  NHANVIEN (MANHANVIEN)
)
GO

CREATE TABLE MONHOC 
(
	MAMONHOC INT IDENTITY PRIMARY KEY,
	TENMONHOC NVARCHAR (20),
	SODVTINCHI INT,
	MAKHOA INT,
	FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA)
)
GO

CREATE TABLE MONHOC_LOP 
(
	MALOP INT,
	MAMONHOC INT,
	HOCKY NVARCHAR(25),
	MANHANVIEN INT,
	PRIMARY KEY (MALOP, MAMONHOC),
	FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN (MANHANVIEN),
	FOREIGN KEY (MALOP ) REFERENCES LOP (MALOP),
	FOREIGN KEY (MAMONHOC) REFERENCES MONHOC (MAMONHOC)
)
GO

CREATE TABLE DIEMTHI 
(
	MAMONHOC INT,
	MSSV INT, 
	DIEMHESO1 TINYINT NOT NULL,
	DIEMHESO2 TINYINT NOT NULL,
	DIEMTHI TINYINT NOT NULL,
	DIEMTRUNGBINH TINYINT,
	XEPLOAI NVARCHAR(10),
	PRIMARY KEY (MAMONHOC, MSSV),
	FOREIGN KEY (MSSV) REFERENCES SINHVIEN (MSSV),
	FOREIGN KEY (MAMONHOC) REFERENCES MONHOC (MAMONHOC)
)
GO

select * from NHANVIEN